CREATE TABLE "DEVELOP"."CARGA_MOVIL" 
   (	"ID" NUMBER(10,0) DEFAULT "DEVELOP"."S_CARGA".nextval NOT NULL ENABLE, 
	"FECHA" TIMESTAMP (6), 
	"REGISTROS" NUMBER(10,0), 
	"USUARIO" VARCHAR2(100), 
	 CONSTRAINT "CARGA_MOVIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV" ;


CREATE TABLE "DEVELOP"."CARGA_MOVIL_DETALLE" 
   (	"ID" NUMBER(10,0) DEFAULT "DEVELOP"."S_CARGA_DETALLE".nextval NOT NULL ENABLE, 
	"ENTIDAD" VARCHAR2(100), 
	"REGISTROS" NUMBER(10,0), 
	"ID_CARGA_MOVIL" NUMBER(*,0), 
	 CONSTRAINT "CARGA_MOVIL_DETALLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV"  ENABLE, 
	 CONSTRAINT "FK_CARGA_MOVIL" FOREIGN KEY ("ID_CARGA_MOVIL")
	  REFERENCES "DEVELOP"."CARGA_MOVIL" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEV" ;


///eliminar

BEGIN
DELETE FROM FNBINFSAL WHERE FECHA_CREACION >= DATE '2021-02-15';

DELETE FROM FNBNUCVIV_FNCPERSON WHERE FECHA_CREACION >= DATE '2021-02-15';

DELETE FROM FNCPERSON f WHERE FECHA_CREACION >= DATE '2021-02-15';

DELETE FROM FNBNUCVIV_FVCCONVIV ff WHERE FECHA_CREACION >= DATE '2021-02-15';

DELETE FROM FNBNUCVIV WHERE FECHA_CREACION >= DATE '2021-02-15';
END;
